version: "3.8"  // 도커 컴포즈 버전

services:
  frontend:
    image: nginx:latest // 최신 nginx 이미지 
    container_name: calendar-frontend
    ports:
      - "3000:80"  # 호스트 3000번과 컨테이너 80번 연결
    volumes:
      - ./frontend:/usr/share/nginx/html:ro  # 로컬 frontend 코드 → 읽기 전용의 nginx HTML
    networks:
      - calendar-net  # 백엔드랑 같은 네트워크로 묶어주기

  backend:
    build:
      context: ./backend  # ./backend 디렉토리에서 이미지 빌드함
    container_name: calendar-backend
    ports:
      - "5000:5000"  # 호스트 5000와 컨테이너 5000
    volumes:
      - ./db:/app/db  # db 디렉토리 마운트하기
      - ./frontend:/app/frontend  # 필요 시 프론트 접근위해
    working_dir: /app  # 작업 디렉토리 
    command: python app.py  # 컨테이너 실행 시 이 명령으로 시작하기
    networks:
      - calendar-net  # 동일 네트워크
    restart: unless-stopped  # 자동 재시작

networks:
  calendar-net:
    driver: bridge  # 기본 브릿지 네트워크



