version: "3.8"

services:
  frontend:
    image: nginx:latest
    container_name: calendar-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - calendar-net

  backend:
    build:
      context: ./backend
    container_name: calendar-backend
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
      - ./frontend:/app/frontend
    working_dir: /app
    command: python app.py
    networks:
      - calendar-net
    restart: unless-stopped

networks:
  calendar-net:
    driver: bridge


